### ISSUE TITLE
pages don't reformat well for mobile

### ISSUE THREAD

**Issue by pvjones** [burninators/my-family-story#115]

**Comment by juliecoding** [comment]
Could you be more specific, @pvjones ? Which pages did you mean?

**Comment by pvjones** [comment]
uhhhhhh....

**Comment by pvjones** [comment]
@barrycann was this from when we were looking at some of elements right before presenting? I can't remember which ones.

**Comment by juliecoding** [comment]
I fixed the prints modal, so I am going to close this issue.
