### ISSUE TITLE
Home:  Create FAQs Page and Connect "Learn More" Links to it

### ISSUE THREAD

**Issue by barrycann** [burninators/my-family-story#120]
I created an FAQs page for the three “LEARN MORE” links to connect to. It should be clear where on the page the “learn more” links should go to. The text is in the WebsiteMockup.ai file and I made a JPG of the page (both in the Website Mockup folder on my Drive)

**Comment by juliecoding** [comment]
Can someone else take this one? I don't have a program to open the WebsiteMockup.ai file.

**Comment by juliecoding** [comment]
Actually, if all she meant was direct each of the 3 "Learn More" <a> tags on the homepage to the FAQ page, I've done that.
