### ISSUE TITLE
Order: Ensure that Thumbnail for Photos uploaded on Portrait Pages Work

### ISSUE THREAD

**Issue by barrycann** [burninators/my-family-story#130]

**Comment by barrycann** [comment]
Client says she sees a generic photo icon.

**Comment by pvjones** [comment]
I think we'll have to check this with her in person. It's working for me. Either of you guys seen this problem?

**Comment by juliecoding** [comment]
I'm also having this problem. It may have to do with our Amazon settings--like maybe we've told it to accept uploads from certain IP addresses?
