### ISSUE TITLE
Checkout:  "Printed Copies" should not show when no printed copies selected

### ISSUE THREAD

**Issue by barrycann** [burninators/my-family-story#133]
From client:  "Can the “Printed Copies” line not populate if the customer doesn’t order them? If it has to populate, can it read “0” in the QUANTITY column?"

**Comment by barrycann** [comment]
Working on this

**Comment by juliecoding** [comment]
Oops, sorry Barry!

**Comment by barrycann** [comment]
Confirmed as fixed.
