### ISSUE TITLE
Checkout:  Hide Shipping Info Fields if Customer is only Ordering Digital Copy

### ISSUE THREAD

**Issue by barrycann** [burninators/my-family-story#135]
From client:  "When the CARD INFO / SHIPPING INFO window pops up, is there a way to not have the shipping info fields populate at all if the customer is only ordering a digital copy?"

**Comment by juliecoding** [comment]
Dibs.

**Comment by juliecoding** [comment]
Boom. She done.

**Comment by juliecoding** [comment]
J/K! Wrong issue. :P

**Comment by barrycann** [comment]
I've completed this.  Just waiting on the pull request to be approved.

**Comment by pvjones** [comment]
👍
